import React from 'react';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import Navigator from './components/navbar.tsx';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navigator></Navigator>
        <main>{children}</main>
        {/* Footer */}
      <footer className="bg-gray-100 py-4">
        <p className="text-center text-gray-500 text-sm">
          © 2024 Indian Museums. All rights reserved.
        </p>
      </footer>
      </body>
    </html>
  );
}
